pipeline{
    agent any
    environment{
        PROJECT = "Expense-Practice"
        ENV = "PROD"
    }
    parameters{
        choice(name: 'PROJECT', choices: ['Expense', 'Robshop', 'Carpool'], description: 'Project Name')
        choice(name: 'ENV', choices: ['DEV', 'QA', 'PROD'], description: 'Environment to deploy')
    }
    stages{
        stage('Build'){
            steps{
                script{
                   echo "Project: ${params.PROJECT}"
                    echo "Environment: ${params.ENV}"

                    sh """
                        echo "Building ${params.PROJECT}"
                        echo "Deploying to ${params.ENV}"
                    """
                }
            }
        }
        stage('Test'){
            steps{
                script{
                    sh """
                        echo "Running Tests"
                    """
                }
            }
        }
        stage('Deploy'){
            steps{
                script{
                    if (ENV == "PROD") {
                input(
                    message: "Do you want to deploy to PROD?",
                    ok: "Deploy"
                )
            }
                }
                
            script{
                sh """
                    echo "Deploying to ${ENV}-${PROJECT}-test"
                """
            }
            }
        }
    }
    post{
        always{
            echo "This will always run"
        }
        success{
            echo "This will run only if successful"
        }
        failure{
            echo "This will run only if failed"
        }
    }
}